### PR TITLE
Incorrect letter in new note

### PR DESCRIPTION
**Pull request by jrjenk**
Being chased by those pesky velociraptors caused a slight typo, I think you have an 's' where you meant to have a 't'

### CODE REVIEW

**Comment by weaverryan** [comment]
doh! Thanks @jrjenk :)

**Comment by weaverryan** [comment]
Btw, your pull request text is being MUCH enjoyed in our KnpU Slack channel :D

**Comment by Leannapelham** [comment]
Ha! That's hilarious

**Comment by jrjenk** [comment]
Hey, after watching all the various Jurassic themed tutorials I felt the need to contribute.

**Pull request merged**
