### PR TITLE
Code blocks for the ch8 and ch9

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Resolve ch8 and ch9 in #12

### CODE REVIEW

**Comment by weaverryan** [comment]
:+1: a few small changes, but nothing big. The one interesting one is that _sometimes_ its helpful to be able to show code blocks of a vendor class - like MinkExtension. I try not to overdo it (because it's kind of a hack), but in these cases, I commit the vendor file to the master branch (well, `behat3` in this case) and in order to use it my code blocks. So, I did that here - and it's ok to do it in the future :).

**Comment by bocharsky-bw** [comment]
I thought about to add `MinkExtension` from vendors, but should we add this file to the our VCS?

**Comment by weaverryan** [comment]
Since the code blocks can only build files that are in the vcs, we must add them. So yes - I added MinkExtension to vcs, which is kind of hacky but ok :)

**Comment by bocharsky-bw** [comment]
Then maybe we should add a next line to the `.gitignore`?

```
/vendor/
!vendor/behat/mink-extension/src/Behat/MinkExtension/Context/Mink/MinkContext.php
```

**Comment by weaverryan** [comment]
@bocharsky-bw we could do that - I force added the file anyways - so I don't think this line will make any difference, right?

**Comment by bocharsky-bw** [comment]
I thought any changes in this file will be ignored by vsc, but seems vsc following its changes, so that's OK.

**Comment by weaverryan** [comment]
Yep - it won't follow changes, BUT you can override that with a git add -f filename :)

**Comment by bocharsky-bw** [comment]
Don't know that, thanks! :)

**Pull request merged**
