### PR TITLE
Add code blocks for the ch11 (suites)

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Resolve ch11-suites in #12

### CODE REVIEW

**Comment by weaverryan** [comment]
:+1: - nice job including the `CommandLineProcessContext` to show "all" of it, but try to hide some less important pieces for space. I did change a few code blocks on this one - for `behat.yml` - sometimes we would hide the `default` and `suites` keys, so when you looked at the code-block, the code we showed was kind of floating in the middle of nowhere - the context wasn't obvious enough. Here's an example:

screen shot 2015-11-09 at 6 36 26 pm

If you ever disagree, let me know! We're both 2 developers, finding the perfect balance that _we_ would want included (and either way, it's not a huge deal, since the code blocks expand - yay!) :)

**Comment by bocharsky-bw** [comment]
:+1: for saving space! Anyways, code blocks really can be expanded if need :)

**Comment by weaverryan** [comment]
@bocharsky-bw actually, I did the opposite - I added a little bit _more_ code to the screenshot (screenshot was the original) - I changed it to include more lines by default :innocent:

**Comment by bocharsky-bw** [comment]
Oh, I understood an idea wrong :)

I shorten it sometimes.. I'll try to add more context in such cases.

**Pull request merged**
