### PR TITLE
Add code blocks to the ch13 (control-database)

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Resolve `ch13-control-database` in #12

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
For this chapter the difference is: `ThereIsAnAdminUserWithPassword()` in the screencast and `ThereIsAUserWithPassword()` in the code blocks. Does it very bad here? Should we change it in source code?

**Comment by weaverryan** [comment]
I think we should change this one - seem just important enough. Are you able to make that change? If you are, do it for this PR :)

**Comment by bocharsky-bw** [comment]
@weaverryan I tried to do it but I'm not sure that it happened.
There're my steps:
- Move to the certain step with `tuts move bootstrap-load-symfony`
- Rename method to `ThereIsAnAdminUserWithPassword` in `FeatureContext.php`
- Commit this changes in `_tuts/behat3/bootstrap-load-symfony` branch
- Checkout to the `code-blocks-ch13` branch
- Compile changes with `tuts compile`, commit them and push to the `code-blocks-ch13` branch

I did something wrong?

**Comment by weaverryan** [comment]
@bocharsky-bw I think you're really close - it's a little tricky, especially to do it on a branch. I think these are the correct steps:
- Checkout to the `code-blocks-ch13` branch. Make sure it is in sync with `behat3` just in case
- Move to the certain step with `tuts move bootstrap-load-symfony`
- Rename method to `ThereIsAnAdminUserWithPassword` in `FeatureContext.php`
- Commit this changes to whatever branch you're on.
- Compile changes with `tuts compile`. This will commit the changes to your `code-blocks-ch13` branch. Push that.
- Run `tuts reset` to kill all of the branches for the steps

Now, to actually update the code block, you'll need to go into the code block gui and change the `sha` to be the latest sha on your `code-blocks-ch13` branch. That will allow the code blocks gui to see your latest code changes.

I'd revert your changes to `_tuts/steps.json` before trying this - and maybe also run `tuts2 reset` on the `behat3` branch to "clear out all the branches". Ultimately, this PR should have changes to `_tuts/steps.json` _and_ at least one `.diff` file in `_tuts/`.

Let me know if that makes sense! It's still a very technical and delicate tool - especially when working _not_ on the master/behat3 branch.

**Comment by bocharsky-bw** [comment]
Yeah, it works! Seems the problem was that I did checkout back to the `code-blocks-ch13` before running `tuts compile`. But there're a lot of file was changed in `_tuts`...  I think it's correct, right?

**Comment by weaverryan** [comment]
:+1: Yes, it's because the sha is stored in the diff's, which we really don't need. Diffs are still quite a mysterious (and delicate) thing - I'd like to learn more about them and see if the sha's can be removed from those files.

**Pull request merged**
